spring:
  application:
    name: AssignmentSystem
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: assignment-system-spring
            client-secret: v7mfb44Ols6mGXO96MMsT7TEW8eQ3RnL
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Assignment
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Assignment/protocol/openid-connect/certs

server:
  port: 9789
